export const BRC_EDU_BLOB_TRIGGER_PATH = "brc-edu-resources/brc-edu/latest/{name}";
export const BRC_EDU_STORAGE_CONNECTION = "BRC_EDU_STORAGE_CONNECTION";
export const RED_BRC_EDU_SYNC_SECRET_HEADER = "x-red-edu-sync-secret";

export const RED_BRC_YOUTUBE_SYNC_ENDPOINT_ENV = "RED_BRC_YOUTUBE_SYNC_ENDPOINT";
export const RED_BRC_YOUTUBE_SYNC_SECRET_ENV = "RED_BRC_YOUTUBE_SYNC_SECRET";
export const RED_BRC_YOUTUBE_SYNC_SCHEDULE_ENV = "BRC_YOUTUBE_SYNC_SCHEDULE";
export const RED_BRC_YOUTUBE_WEBHOOK_FORWARD_ENV = "RED_BRC_YOUTUBE_WEBHOOK_FORWARD";
