import { brcFetch, extractListItems, type JsonRecord } from "./shared.js";
import { redServerConfig } from "./config/server_config.js";

const SENSITIVE_FIELD_NAMES = new Set(
  [
    "apiKey",
    "api_key",
    "apikey",
    "key",
    "token",
    "accessToken",
    "refreshToken",
    "password",
    "secret",
    "authorization",
  ].map((name) => name.toLowerCase())
);

const PROCESSING_ENDPOINTS = [
  {
    id: "companySettings_paged",
    path: "/v1/companySettings?page=1&pageSize=20",
    note: "Same path used by getCompanyProcessingSettings.",
  },
  {
    id: "companySettings_list",
    path: "/v1/companySettings",
    note: "Same base path used by brc_list_company_settings.",
  },
  {
    id: "companySetupConfig",
    path: "/v1/companySetupConfig",
    note: "Company setup root; may contain generalDetails, options, referenceSettings.",
  },
  {
    id: "companyOptions",
    path: "/v1/companySetupConfig/getCompanyOptions",
    note: "Company options including vocrSettingValue used by cash receipt settings.",
  },
  {
    id: "financialYear",
    path: "/v1/companySetupConfig/getFinancialYear",
    note: "Financial year; included for comparison only.",
  },
] as const;

/** Field aliases currently searched by getCompanyProcessingSettings findValue(). */
export const PROCESSING_SETTINGS_MAPPER_ALIASES = [
  "nominalLedger",
  "nominalLedgerEnabled",
  "autogenerateNominalCodes",
  "autoGenerateNominalCodes",
  "enableVatOnCashReceipts",
  "vatOnCashReceipts",
  "enableVatCashReceipts",
  "vocrEnabled",
  "enterVatManuallyOnCashReceipts",
  "manualVatOnCashReceipts",
  "manualVocr",
  "calculateVocrBasedOnAllocationOfCashReceipts",
  "calculateVatBasedOnAllocationOfCashReceipts",
  "allocationBasedVocr",
  "marginVatScheme",
  "marginVatSchemeEnabled",
  "creditInputForReverseChargeVat",
  "creditInputReverseChargeVat",
  "reverseChargeCreditInput",
  "otherEuSalesDefault",
  "otherEUSalesDefault",
  "otherEuPurchasesDefault",
  "otherEUPurchasesDefault",
  "allowEntryOfGrossPriceInSalesInvoicing",
  "allowGrossPriceInSalesInvoicing",
  "grossPriceSalesInvoicing",
  "vatDiscrepancyAllowed",
  "vatDiscrepancyAllowedInPurchaseAndSalesEntries",
  "customerPaymentTerms",
  "customerPaymentTermsEnabled",
  "customerPaymentTermsDays",
  "customerPaymentNoOfDays",
  "customerPaymentTermsBasis",
  "customerPaymentTermsType",
  "supplierPaymentTerms",
  "supplierPaymentTermsEnabled",
  "supplierPaymentTermsDays",
  "supplierPaymentNoOfDays",
  "supplierPaymentTermsBasis",
  "supplierPaymentTermsType",
  "defaultDebtorStatementMinimumBalance",
  "debtorStatementMinimumBalance",
  "referenceSettings",
  "sales",
  "purchases",
  "quotes",
  "debtorsJournal",
  "creditorsJournal",
  "autoGenerateSalesReference",
  "autoGeneratePurchasesReference",
  "autoGenerateQuotesReference",
  "autoGenerateDebtorsJournalReference",
  "autoGenerateCreditorsJournalReference",
] as const;

function isSensitiveKey(key: string): boolean {
  return SENSITIVE_FIELD_NAMES.has(key.toLowerCase());
}

function describeValue(value: unknown): unknown {
  if (value === null) return null;
  if (value === undefined) return undefined;

  const valueType = typeof value;

  if (valueType === "string") {
    const text = value as string;
    return {
      _type: "string",
      length: text.length,
      preview: text.length <= 120 ? text : `${text.slice(0, 120)}…`,
    };
  }

  if (valueType === "number" || valueType === "boolean") {
    return value;
  }

  if (Array.isArray(value)) {
    return {
      _type: "array",
      length: value.length,
      firstItemType:
        value.length > 0 ? typeof value[0] : undefined,
    };
  }

  if (valueType === "object") {
    const record = value as JsonRecord;
    return {
      _type: "object",
      keys: Object.keys(record),
    };
  }

  return { _type: valueType };
}

export function shallowRedactedRecord(record: JsonRecord): JsonRecord {
  const shallow: JsonRecord = {};

  for (const [key, value] of Object.entries(record)) {
    shallow[key] = isSensitiveKey(key) ? "<REDACTED>" : describeValue(value);
  }

  return shallow;
}

function firstRecord(value: unknown): JsonRecord {
  if (Array.isArray(value)) {
    const first = value.find(
      (item) => item && typeof item === "object" && !Array.isArray(item)
    );
    return first ? (first as JsonRecord) : {};
  }

  if (value && typeof value === "object" && !Array.isArray(value)) {
    const record = value as JsonRecord;

    if (Array.isArray(record.items)) return firstRecord(record.items);
    if (Array.isArray(record.value)) return firstRecord(record.value);
    if (Array.isArray(record.data)) return firstRecord(record.data);

    return record;
  }

  return {};
}

function extractXmlTagNames(value: unknown): string[] {
  if (typeof value !== "string" || !value.includes("<")) return [];

  const tags = new Set<string>();
  const pattern = /<([A-Za-z][A-Za-z0-9]*)\b/g;

  for (const match of value.matchAll(pattern)) {
    tags.add(match[1]);
  }

  return [...tags].sort();
}

type EndpointDiagnostic = {
  id: string;
  path: string;
  note: string;
  ok: boolean;
  error?: string;
  responseTopLevelType: string;
  responseTopLevelKeys: string[];
  listItemCount: number;
  firstListItemKeys: string[];
  firstListItemShallow: JsonRecord;
  firstRecordFromMapperKeys: string[];
  firstRecordFromMapperShallow: JsonRecord;
  xmlTagNamesInFirstListItemValue: string[];
  objectShallow: JsonRecord;
  nestedSectionKeys: JsonRecord;
};

async function probeEndpoint(
  companyName: string,
  endpoint: (typeof PROCESSING_ENDPOINTS)[number]
): Promise<EndpointDiagnostic> {
  const base: Omit<EndpointDiagnostic, "ok" | "error"> = {
    id: endpoint.id,
    path: endpoint.path,
    note: endpoint.note,
    responseTopLevelType: "unknown",
    responseTopLevelKeys: [],
    listItemCount: 0,
    firstListItemKeys: [],
    firstListItemShallow: {},
    firstRecordFromMapperKeys: [],
    firstRecordFromMapperShallow: {},
    xmlTagNamesInFirstListItemValue: [],
    objectShallow: {},
    nestedSectionKeys: {},
  };

  try {
    const response = await brcFetch(companyName, endpoint.path);
    const listItems = extractListItems(response);
    const mappedFirstRecord = firstRecord(response);
    const firstListItem = listItems[0] ?? {};
    const firstValue = firstListItem.value ?? firstListItem;

    base.responseTopLevelType = Array.isArray(response)
      ? "array"
      : response === null
        ? "null"
        : typeof response;
    base.responseTopLevelKeys =
      response && typeof response === "object" && !Array.isArray(response)
        ? Object.keys(response as JsonRecord)
        : [];
    base.listItemCount = listItems.length;
    base.firstListItemKeys = Object.keys(firstListItem);
    base.firstListItemShallow = shallowRedactedRecord(firstListItem);
    base.firstRecordFromMapperKeys = Object.keys(mappedFirstRecord);
    base.firstRecordFromMapperShallow = shallowRedactedRecord(mappedFirstRecord);
    base.xmlTagNamesInFirstListItemValue = extractXmlTagNames(firstValue);

    if (
      response &&
      typeof response === "object" &&
      !Array.isArray(response)
    ) {
      const record = response as JsonRecord;
      base.objectShallow = shallowRedactedRecord(record);

      for (const section of [
        "options",
        "generalDetails",
        "referenceSettings",
        "financialYear",
      ]) {
        const nested = record[section];
        if (nested && typeof nested === "object" && !Array.isArray(nested)) {
          base.nestedSectionKeys[section] = Object.keys(nested as JsonRecord);
        }
      }
    }

    return { ...base, ok: true };
  } catch (error) {
    return {
      ...base,
      ok: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

export async function diagnoseCompanyProcessingSettings(companyName: string) {
  if (!redServerConfig.allowDevMode) {
    return {
      devModeActive: false,
      message:
        "Development diagnostics are not available in the current Red deployment.",
      companyName,
    };
  }

  const endpointsProbed = await Promise.all(
    PROCESSING_ENDPOINTS.map((endpoint) => probeEndpoint(companyName, endpoint))
  );

  const keysFound = new Set<string>();
  const xmlTagsFound = new Set<string>();

  for (const endpoint of endpointsProbed) {
    endpoint.responseTopLevelKeys.forEach((key) => keysFound.add(key));
    endpoint.firstListItemKeys.forEach((key) => keysFound.add(key));
    endpoint.firstRecordFromMapperKeys.forEach((key) => keysFound.add(key));
    Object.keys(endpoint.objectShallow).forEach((key) => keysFound.add(key));
    endpoint.xmlTagNamesInFirstListItemValue.forEach((tag) => xmlTagsFound.add(tag));

    for (const sectionKeys of Object.values(endpoint.nestedSectionKeys)) {
      if (Array.isArray(sectionKeys)) {
        sectionKeys.forEach((key) => keysFound.add(String(key)));
      }
    }
  }

  const aliasMatches = PROCESSING_SETTINGS_MAPPER_ALIASES.filter((alias) => {
    const normalised = alias.toLowerCase().replace(/[^a-z0-9]/g, "");
    return [...keysFound, ...xmlTagsFound].some(
      (key) => key.toLowerCase().replace(/[^a-z0-9]/g, "") === normalised
    );
  });

  return {
    devModeActive: true,
    message:
      "Temporary dev-only diagnostic for company processing/options API field discovery.",
    companyName,
    operatorNote:
      "Operator-only output. Shallow values only; sensitive keys redacted. Do not paste into customer chat.",
    endpointsProbed,
    getCompanyProcessingSettingsPath: "/v1/companySettings?page=1&pageSize=20",
    mapperAliasesSearched: [...PROCESSING_SETTINGS_MAPPER_ALIASES],
    shallowKeysFound: [...keysFound].sort(),
    xmlTagNamesInFirstCompanySettingValue: [...xmlTagsFound].sort(),
    mapperAliasMatchesFound: aliasMatches,
  };
}
