import type { ToolAnnotations } from "@modelcontextprotocol/sdk/types.js";

export type ExplicitToolAnnotations = ToolAnnotations & {
  readOnlyHint: boolean;
  openWorldHint: boolean;
  destructiveHint: boolean;
};

const READ_ONLY = {
  readOnlyHint: true,
  openWorldHint: false,
  destructiveHint: false,
} as const satisfies ExplicitToolAnnotations;

const PRIVATE_WRITE = {
  readOnlyHint: false,
  openWorldHint: false,
  destructiveHint: false,
} as const satisfies ExplicitToolAnnotations;

const PRIVATE_DESTRUCTIVE = {
  readOnlyHint: false,
  openWorldHint: false,
  destructiveHint: true,
} as const satisfies ExplicitToolAnnotations;

const EXTERNAL_DESTRUCTIVE = {
  readOnlyHint: false,
  openWorldHint: true,
  destructiveHint: true,
} as const satisfies ExplicitToolAnnotations;

/**
 * Explicit MCP safety hints, audited against each registered handler's actual
 * reads, writes, external effects, and reversibility. Keep this fail-closed:
 * getToolAnnotations throws when a registration has no exact entry here.
 */
export const TOOL_ANNOTATIONS = {
  brc_batch_cash_payments: PRIVATE_DESTRUCTIVE,
  brc_batch_cash_receipts: PRIVATE_DESTRUCTIVE,
  brc_batch_customers: PRIVATE_DESTRUCTIVE,
  brc_batch_payments: PRIVATE_DESTRUCTIVE,
  brc_batch_products: PRIVATE_DESTRUCTIVE,
  brc_batch_purchases: PRIVATE_DESTRUCTIVE,
  brc_batch_quotes: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_credit_notes: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_entries: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_invoices: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_reps: PRIVATE_DESTRUCTIVE,
  brc_batch_suppliers: PRIVATE_DESTRUCTIVE,
  brc_check_transaction_settings: READ_ONLY,
  brc_clear_all_company_api_keys: PRIVATE_DESTRUCTIVE,
  brc_clear_audit_log: PRIVATE_DESTRUCTIVE,
  brc_clear_company_api_key: PRIVATE_DESTRUCTIVE,
  brc_close_quote: PRIVATE_WRITE,
  brc_company_readiness_check: READ_ONLY,
  brc_confirm_company_connection: PRIVATE_WRITE,
  brc_create_accrual: PRIVATE_DESTRUCTIVE,
  brc_create_bank_account: PRIVATE_WRITE,
  brc_create_cash_payment: PRIVATE_DESTRUCTIVE,
  brc_create_cash_receipt: PRIVATE_DESTRUCTIVE,
  brc_create_customer: PRIVATE_WRITE,
  brc_create_nominal_journal_batch: PRIVATE_DESTRUCTIVE,
  brc_create_payment: PRIVATE_DESTRUCTIVE,
  brc_create_prepayment: PRIVATE_DESTRUCTIVE,
  brc_create_product: PRIVATE_WRITE,
  brc_create_purchase: PRIVATE_DESTRUCTIVE,
  brc_create_purchase_gen_ref: PRIVATE_DESTRUCTIVE,
  brc_create_quote: PRIVATE_WRITE,
  brc_create_quote_gen_ref: PRIVATE_WRITE,
  brc_create_sales_credit_note: PRIVATE_DESTRUCTIVE,
  brc_create_sales_credit_note_gen_ref: PRIVATE_DESTRUCTIVE,
  brc_create_sales_entry: PRIVATE_DESTRUCTIVE,
  brc_create_sales_invoice: PRIVATE_DESTRUCTIVE,
  brc_create_sales_invoice_gen_ref: PRIVATE_DESTRUCTIVE,
  brc_create_sales_rep: PRIVATE_WRITE,
  brc_create_supplier: PRIVATE_WRITE,
  brc_delete_accrual: PRIVATE_DESTRUCTIVE,
  brc_delete_allocation_resolver: PRIVATE_DESTRUCTIVE,
  brc_delete_bank_account: PRIVATE_DESTRUCTIVE,
  brc_delete_cash_payment: PRIVATE_DESTRUCTIVE,
  brc_delete_cash_receipt: PRIVATE_DESTRUCTIVE,
  brc_delete_customer: PRIVATE_DESTRUCTIVE,
  brc_delete_nominal_journal_batch: PRIVATE_DESTRUCTIVE,
  brc_delete_payment: PRIVATE_DESTRUCTIVE,
  brc_delete_prepayment: PRIVATE_DESTRUCTIVE,
  brc_delete_product: PRIVATE_DESTRUCTIVE,
  brc_delete_purchase: PRIVATE_DESTRUCTIVE,
  brc_delete_quote: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_credit_note: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_entry: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_invoice: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_rep: PRIVATE_DESTRUCTIVE,
  brc_delete_supplier: PRIVATE_DESTRUCTIVE,
  brc_dev_diagnose_company_processing_settings: READ_ONLY,
  brc_find_help_resources: READ_ONLY,
  brc_generate_sales_invoice_from_quote: PRIVATE_DESTRUCTIVE,
  brc_generate_support_report: READ_ONLY,
  brc_get_accrual: READ_ONLY,
  brc_get_bank_account: READ_ONLY,
  brc_get_cash_payment: READ_ONLY,
  brc_get_cash_receipt: READ_ONLY,
  brc_get_company_api_key_status: READ_ONLY,
  brc_get_company_logo: READ_ONLY,
  brc_get_company_processing_settings: READ_ONLY,
  brc_get_company_reference_settings: READ_ONLY,
  brc_get_company_setup_config: READ_ONLY,
  brc_get_connection_store_diagnostics: READ_ONLY,
  brc_get_customer: READ_ONLY,
  brc_get_customer_opening_balance: READ_ONLY,
  brc_get_deployment_policy: READ_ONLY,
  brc_get_dev_mode_details: READ_ONLY,
  brc_get_financial_year: READ_ONLY,
  brc_get_help_resource_details: READ_ONLY,
  brc_get_nom_ac_ledger_by_ids: READ_ONLY,
  brc_get_nominal_account_ledger_by_id: READ_ONLY,
  brc_get_nominal_journal_batch: READ_ONLY,
  brc_get_payment: READ_ONLY,
  brc_get_prepayment: READ_ONLY,
  brc_get_product: READ_ONLY,
  brc_get_purchase: READ_ONLY,
  brc_get_quote: READ_ONLY,
  brc_get_sales_credit_note: READ_ONLY,
  brc_get_sales_entry: READ_ONLY,
  brc_get_sales_invoice: READ_ONLY,
  brc_get_sales_rep: READ_ONLY,
  brc_get_supplier: READ_ONLY,
  brc_get_supplier_opening_balance: READ_ONLY,
  brc_grouped_nominal_accounts_report: READ_ONLY,
  brc_list_accounts: READ_ONLY,
  brc_list_accruals: READ_ONLY,
  brc_list_allocated_transactions: READ_ONLY,
  brc_list_allocation_resolvers: READ_ONLY,
  brc_list_analysis_categories: READ_ONLY,
  brc_list_audit_log: READ_ONLY,
  brc_list_bank_accounts: READ_ONLY,
  brc_list_book_tran_types: READ_ONLY,
  brc_list_cash_payments: READ_ONLY,
  brc_list_cash_receipts: READ_ONLY,
  brc_list_category_types: READ_ONLY,
  brc_list_company_contexts: READ_ONLY,
  brc_list_company_settings: READ_ONLY,
  brc_list_customer_account_trans: READ_ONLY,
  brc_list_customer_op_bal_trans: READ_ONLY,
  brc_list_customer_quotes: READ_ONLY,
  brc_list_customers: READ_ONLY,
  brc_list_customers_without_dormant: READ_ONLY,
  brc_list_nominal_accounts: READ_ONLY,
  brc_list_nominal_journal_batches: READ_ONLY,
  brc_list_owner_type_groups: READ_ONLY,
  brc_list_owner_types: READ_ONLY,
  brc_list_payments: READ_ONLY,
  brc_list_prepayments: READ_ONLY,
  brc_list_product_types: READ_ONLY,
  brc_list_products: READ_ONLY,
  brc_list_products_without_dormant: READ_ONLY,
  brc_list_purchases: READ_ONLY,
  brc_list_quotes: READ_ONLY,
  brc_list_sales: READ_ONLY,
  brc_list_sales_credit_notes: READ_ONLY,
  brc_list_sales_entries: READ_ONLY,
  brc_list_sales_invoices: READ_ONLY,
  brc_list_sales_reps: READ_ONLY,
  brc_list_supplier_account_trans: READ_ONLY,
  brc_list_supplier_op_bal_trans: READ_ONLY,
  brc_list_suppliers: READ_ONLY,
  brc_list_user_defined_fields: READ_ONLY,
  brc_list_vat_analysis_types: READ_ONLY,
  brc_list_vat_categories: READ_ONLY,
  brc_list_vat_rates: READ_ONLY,
  brc_list_vat_types: READ_ONLY,
  brc_multi_company_nom_ac_report: READ_ONLY,
  brc_open_edu_admin: READ_ONLY,
  brc_process_vat_category_rates: PRIVATE_DESTRUCTIVE,
  brc_red_help: READ_ONLY,
  brc_reopen_quote: PRIVATE_WRITE,
  brc_resolve_book_transaction_type: READ_ONLY,
  brc_route_request: READ_ONLY,
  brc_send_email_statement: EXTERNAL_DESTRUCTIVE,
  brc_send_quote_email: EXTERNAL_DESTRUCTIVE,
  brc_send_sales_invoice_email: EXTERNAL_DESTRUCTIVE,
  brc_set_company_api_key: PRIVATE_DESTRUCTIVE,
  brc_start_company_connection: PRIVATE_WRITE,
  brc_update_accrual: PRIVATE_DESTRUCTIVE,
  brc_update_allocations: PRIVATE_DESTRUCTIVE,
  brc_update_bank_account: PRIVATE_DESTRUCTIVE,
  brc_update_cash_payment: PRIVATE_DESTRUCTIVE,
  brc_update_cash_receipt: PRIVATE_DESTRUCTIVE,
  brc_update_customer: PRIVATE_DESTRUCTIVE,
  brc_update_nominal_journal_batch: PRIVATE_DESTRUCTIVE,
  brc_update_payment: PRIVATE_DESTRUCTIVE,
  brc_update_prepayment: PRIVATE_DESTRUCTIVE,
  brc_update_product: PRIVATE_DESTRUCTIVE,
  brc_update_purchase: PRIVATE_DESTRUCTIVE,
  brc_update_quote: PRIVATE_DESTRUCTIVE,
  brc_update_sales_credit_note: PRIVATE_DESTRUCTIVE,
  brc_update_sales_entry: PRIVATE_DESTRUCTIVE,
  brc_update_sales_invoice: PRIVATE_DESTRUCTIVE,
  brc_update_sales_rep: PRIVATE_DESTRUCTIVE,
  brc_update_supplier: PRIVATE_DESTRUCTIVE,
  brc_validate_transaction_date: READ_ONLY,
} as const satisfies Record<string, ExplicitToolAnnotations>;

export type AnnotatedToolName = keyof typeof TOOL_ANNOTATIONS;

/** Human-readable catalogue titles. Exact-key typing prevents drift from the safety registry. */
export const TOOL_TITLES = {
  brc_batch_cash_payments: "Batch Cash Payments",
  brc_batch_cash_receipts: "Batch Cash Receipts",
  brc_batch_customers: "Batch Customers",
  brc_batch_payments: "Batch Payments",
  brc_batch_products: "Batch Products",
  brc_batch_purchases: "Batch Purchases",
  brc_batch_quotes: "Batch Quotes",
  brc_batch_sales_credit_notes: "Batch Sales Credit Notes",
  brc_batch_sales_entries: "Batch Sales Entries",
  brc_batch_sales_invoices: "Batch Sales Invoices",
  brc_batch_sales_reps: "Batch Sales Representatives",
  brc_batch_suppliers: "Batch Suppliers",
  brc_check_transaction_settings: "Check Transaction Settings",
  brc_clear_all_company_api_keys: "Clear All Company API Keys",
  brc_clear_audit_log: "Clear Audit Log",
  brc_clear_company_api_key: "Clear Company API Key",
  brc_close_quote: "Close Quote",
  brc_company_readiness_check: "Check Company Readiness",
  brc_confirm_company_connection: "Confirm Company Connection",
  brc_create_accrual: "Create Accrual",
  brc_create_bank_account: "Create Bank Account",
  brc_create_cash_payment: "Create Cash Payment",
  brc_create_cash_receipt: "Create Cash Receipt",
  brc_create_customer: "Create Customer",
  brc_create_nominal_journal_batch: "Create Nominal Journal Batch",
  brc_create_payment: "Create Payment",
  brc_create_prepayment: "Create Prepayment",
  brc_create_product: "Create Product",
  brc_create_purchase: "Create Purchase",
  brc_create_purchase_gen_ref: "Create Purchase with Generated Reference",
  brc_create_quote: "Create Quote",
  brc_create_quote_gen_ref: "Create Quote with Generated Reference",
  brc_create_sales_credit_note: "Create Sales Credit Note",
  brc_create_sales_credit_note_gen_ref: "Create Sales Credit Note with Generated Reference",
  brc_create_sales_entry: "Create Sales Entry",
  brc_create_sales_invoice: "Create Sales Invoice",
  brc_create_sales_invoice_gen_ref: "Create Sales Invoice with Generated Reference",
  brc_create_sales_rep: "Create Sales Representative",
  brc_create_supplier: "Create Supplier",
  brc_delete_accrual: "Delete Accrual",
  brc_delete_allocation_resolver: "Delete Allocation Resolver",
  brc_delete_bank_account: "Delete Bank Account",
  brc_delete_cash_payment: "Delete Cash Payment",
  brc_delete_cash_receipt: "Delete Cash Receipt",
  brc_delete_customer: "Delete Customer",
  brc_delete_nominal_journal_batch: "Delete Nominal Journal Batch",
  brc_delete_payment: "Delete Payment",
  brc_delete_prepayment: "Delete Prepayment",
  brc_delete_product: "Delete Product",
  brc_delete_purchase: "Delete Purchase",
  brc_delete_quote: "Delete Quote",
  brc_delete_sales_credit_note: "Delete Sales Credit Note",
  brc_delete_sales_entry: "Delete Sales Entry",
  brc_delete_sales_invoice: "Delete Sales Invoice",
  brc_delete_sales_rep: "Delete Sales Representative",
  brc_delete_supplier: "Delete Supplier",
  brc_dev_diagnose_company_processing_settings: "Diagnose Company Processing Settings",
  brc_find_help_resources: "Find Help Resources",
  brc_generate_sales_invoice_from_quote: "Generate Sales Invoice from Quote",
  brc_generate_support_report: "Generate Support Report",
  brc_get_accrual: "Get Accrual",
  brc_get_bank_account: "Get Bank Account",
  brc_get_cash_payment: "Get Cash Payment",
  brc_get_cash_receipt: "Get Cash Receipt",
  brc_get_company_api_key_status: "Get Company API Key Status",
  brc_get_company_logo: "Get Company Logo",
  brc_get_company_processing_settings: "Get Company Processing Settings",
  brc_get_company_reference_settings: "Get Company Reference Settings",
  brc_get_company_setup_config: "Get Company Setup Configuration",
  brc_get_connection_store_diagnostics: "Get Connection Store Diagnostics",
  brc_get_customer: "Get Customer",
  brc_get_customer_opening_balance: "Get Customer Opening Balance",
  brc_get_deployment_policy: "Get Deployment Policy",
  brc_get_dev_mode_details: "Get Development Mode Details",
  brc_get_financial_year: "Get Financial Year",
  brc_get_help_resource_details: "Get Help Resource Details",
  brc_get_nom_ac_ledger_by_ids: "Get Nominal Account Ledgers by IDs",
  brc_get_nominal_account_ledger_by_id: "Get Nominal Account Ledger by ID",
  brc_get_nominal_journal_batch: "Get Nominal Journal Batch",
  brc_get_payment: "Get Payment",
  brc_get_prepayment: "Get Prepayment",
  brc_get_product: "Get Product",
  brc_get_purchase: "Get Purchase",
  brc_get_quote: "Get Quote",
  brc_get_sales_credit_note: "Get Sales Credit Note",
  brc_get_sales_entry: "Get Sales Entry",
  brc_get_sales_invoice: "Get Sales Invoice",
  brc_get_sales_rep: "Get Sales Representative",
  brc_get_supplier: "Get Supplier",
  brc_get_supplier_opening_balance: "Get Supplier Opening Balance",
  brc_grouped_nominal_accounts_report: "Grouped Nominal Accounts Report",
  brc_list_accounts: "List Accounts",
  brc_list_accruals: "List Accruals",
  brc_list_allocated_transactions: "List Allocated Transactions",
  brc_list_allocation_resolvers: "List Allocation Resolvers",
  brc_list_analysis_categories: "List Analysis Categories",
  brc_list_audit_log: "List Audit Log",
  brc_list_bank_accounts: "List Bank Accounts",
  brc_list_book_tran_types: "List Book Transaction Types",
  brc_list_cash_payments: "List Cash Payments",
  brc_list_cash_receipts: "List Cash Receipts",
  brc_list_category_types: "List Category Types",
  brc_list_company_contexts: "List Company Contexts",
  brc_list_company_settings: "List Company Settings",
  brc_list_customer_account_trans: "List Customer Account Transactions",
  brc_list_customer_op_bal_trans: "List Customer Opening Balance Transactions",
  brc_list_customer_quotes: "List Customer Quotes",
  brc_list_customers: "List Customers",
  brc_list_customers_without_dormant: "List Active Customers",
  brc_list_nominal_accounts: "List Nominal Accounts",
  brc_list_nominal_journal_batches: "List Nominal Journal Batches",
  brc_list_owner_type_groups: "List Owner Type Groups",
  brc_list_owner_types: "List Owner Types",
  brc_list_payments: "List Payments",
  brc_list_prepayments: "List Prepayments",
  brc_list_product_types: "List Product Types",
  brc_list_products: "List Products",
  brc_list_products_without_dormant: "List Active Products",
  brc_list_purchases: "List Purchases",
  brc_list_quotes: "List Quotes",
  brc_list_sales: "List Sales",
  brc_list_sales_credit_notes: "List Sales Credit Notes",
  brc_list_sales_entries: "List Sales Entries",
  brc_list_sales_invoices: "List Sales Invoices",
  brc_list_sales_reps: "List Sales Representatives",
  brc_list_supplier_account_trans: "List Supplier Account Transactions",
  brc_list_supplier_op_bal_trans: "List Supplier Opening Balance Transactions",
  brc_list_suppliers: "List Suppliers",
  brc_list_user_defined_fields: "List User-Defined Fields",
  brc_list_vat_analysis_types: "List VAT Analysis Types",
  brc_list_vat_categories: "List VAT Categories",
  brc_list_vat_rates: "List VAT Rates",
  brc_list_vat_types: "List VAT Types",
  brc_multi_company_nom_ac_report: "Multi-Company Nominal Account Report",
  brc_open_edu_admin: "Open Education Administration",
  brc_process_vat_category_rates: "Process VAT Category Rates",
  brc_red_help: "Get Red Help",
  brc_reopen_quote: "Reopen Quote",
  brc_resolve_book_transaction_type: "Resolve Book Transaction Type",
  brc_route_request: "Route Request",
  brc_send_email_statement: "Send Account Statement Email",
  brc_send_quote_email: "Send Quote Email",
  brc_send_sales_invoice_email: "Send Sales Invoice Email",
  brc_set_company_api_key: "Set Company API Key",
  brc_start_company_connection: "Start Company Connection",
  brc_update_accrual: "Update Accrual",
  brc_update_allocations: "Update Allocations",
  brc_update_bank_account: "Update Bank Account",
  brc_update_cash_payment: "Update Cash Payment",
  brc_update_cash_receipt: "Update Cash Receipt",
  brc_update_customer: "Update Customer",
  brc_update_nominal_journal_batch: "Update Nominal Journal Batch",
  brc_update_payment: "Update Payment",
  brc_update_prepayment: "Update Prepayment",
  brc_update_product: "Update Product",
  brc_update_purchase: "Update Purchase",
  brc_update_quote: "Update Quote",
  brc_update_sales_credit_note: "Update Sales Credit Note",
  brc_update_sales_entry: "Update Sales Entry",
  brc_update_sales_invoice: "Update Sales Invoice",
  brc_update_sales_rep: "Update Sales Representative",
  brc_update_supplier: "Update Supplier",
  brc_validate_transaction_date: "Validate Transaction Date",
} as const satisfies Record<AnnotatedToolName, string>;

export type ExplicitToolMetadata = {
  title: string;
  annotations: ExplicitToolAnnotations;
};

export function getToolMetadata(toolName: string): ExplicitToolMetadata {
  const annotations = TOOL_ANNOTATIONS[toolName as AnnotatedToolName];
  const title = TOOL_TITLES[toolName as AnnotatedToolName];
  if (!annotations || !title) {
    throw new Error(
      `MCP tool "${toolName}" has no complete metadata entry. Add a title, readOnlyHint, openWorldHint, and destructiveHint before registering it.`,
    );
  }

  return { title, annotations };
}

export function getToolAnnotations(toolName: string): ExplicitToolAnnotations {
  return getToolMetadata(toolName).annotations;
}
