import type { ToolAnnotations } from "@modelcontextprotocol/sdk/types.js";

export type ExplicitToolAnnotations = ToolAnnotations & {
  readOnlyHint: boolean;
  openWorldHint: boolean;
  destructiveHint: boolean;
};

const READ_ONLY = {
  readOnlyHint: true,
  openWorldHint: false,
  destructiveHint: false,
} as const satisfies ExplicitToolAnnotations;

const PRIVATE_WRITE = {
  readOnlyHint: false,
  openWorldHint: false,
  destructiveHint: false,
} as const satisfies ExplicitToolAnnotations;

const PRIVATE_DESTRUCTIVE = {
  readOnlyHint: false,
  openWorldHint: false,
  destructiveHint: true,
} as const satisfies ExplicitToolAnnotations;

const EXTERNAL_DESTRUCTIVE = {
  readOnlyHint: false,
  openWorldHint: true,
  destructiveHint: true,
} as const satisfies ExplicitToolAnnotations;

/**
 * Explicit MCP safety hints, audited against each registered handler's actual
 * reads, writes, external effects, and reversibility. Keep this fail-closed:
 * getToolAnnotations throws when a registration has no exact entry here.
 */
export const TOOL_ANNOTATIONS = {
  brc_batch_cash_payments: PRIVATE_DESTRUCTIVE,
  brc_batch_cash_receipts: PRIVATE_DESTRUCTIVE,
  brc_batch_customers: PRIVATE_DESTRUCTIVE,
  brc_batch_payments: PRIVATE_DESTRUCTIVE,
  brc_batch_products: PRIVATE_DESTRUCTIVE,
  brc_batch_purchases: PRIVATE_DESTRUCTIVE,
  brc_batch_quotes: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_credit_notes: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_entries: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_invoices: PRIVATE_DESTRUCTIVE,
  brc_batch_sales_reps: PRIVATE_DESTRUCTIVE,
  brc_batch_suppliers: PRIVATE_DESTRUCTIVE,
  brc_check_transaction_settings: READ_ONLY,
  brc_clear_all_company_api_keys: PRIVATE_DESTRUCTIVE,
  brc_clear_audit_log: PRIVATE_DESTRUCTIVE,
  brc_clear_company_api_key: PRIVATE_DESTRUCTIVE,
  brc_close_quote: PRIVATE_WRITE,
  brc_company_readiness_check: READ_ONLY,
  brc_confirm_company_connection: PRIVATE_WRITE,
  brc_create_accrual: PRIVATE_DESTRUCTIVE,
  brc_create_bank_account: PRIVATE_WRITE,
  brc_create_cash_payment: PRIVATE_DESTRUCTIVE,
  brc_create_cash_receipt: PRIVATE_DESTRUCTIVE,
  brc_create_customer: PRIVATE_WRITE,
  brc_create_nominal_journal_batch: PRIVATE_DESTRUCTIVE,
  brc_create_payment: PRIVATE_DESTRUCTIVE,
  brc_create_prepayment: PRIVATE_DESTRUCTIVE,
  brc_create_product: PRIVATE_WRITE,
  brc_create_purchase: PRIVATE_DESTRUCTIVE,
  brc_create_purchase_gen_ref: PRIVATE_DESTRUCTIVE,
  brc_create_quote: PRIVATE_WRITE,
  brc_create_quote_gen_ref: PRIVATE_WRITE,
  brc_create_sales_credit_note: PRIVATE_DESTRUCTIVE,
  brc_create_sales_credit_note_gen_ref: PRIVATE_DESTRUCTIVE,
  brc_create_sales_entry: PRIVATE_DESTRUCTIVE,
  brc_create_sales_invoice: PRIVATE_DESTRUCTIVE,
  brc_create_sales_invoice_gen_ref: PRIVATE_DESTRUCTIVE,
  brc_create_sales_rep: PRIVATE_WRITE,
  brc_create_supplier: PRIVATE_WRITE,
  brc_delete_accrual: PRIVATE_DESTRUCTIVE,
  brc_delete_allocation_resolver: PRIVATE_DESTRUCTIVE,
  brc_delete_bank_account: PRIVATE_DESTRUCTIVE,
  brc_delete_cash_payment: PRIVATE_DESTRUCTIVE,
  brc_delete_cash_receipt: PRIVATE_DESTRUCTIVE,
  brc_delete_customer: PRIVATE_DESTRUCTIVE,
  brc_delete_nominal_journal_batch: PRIVATE_DESTRUCTIVE,
  brc_delete_payment: PRIVATE_DESTRUCTIVE,
  brc_delete_prepayment: PRIVATE_DESTRUCTIVE,
  brc_delete_product: PRIVATE_DESTRUCTIVE,
  brc_delete_purchase: PRIVATE_DESTRUCTIVE,
  brc_delete_quote: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_credit_note: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_entry: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_invoice: PRIVATE_DESTRUCTIVE,
  brc_delete_sales_rep: PRIVATE_DESTRUCTIVE,
  brc_delete_supplier: PRIVATE_DESTRUCTIVE,
  brc_dev_diagnose_company_processing_settings: READ_ONLY,
  brc_find_help_resources: READ_ONLY,
  brc_generate_sales_invoice_from_quote: PRIVATE_DESTRUCTIVE,
  brc_generate_support_report: READ_ONLY,
  brc_get_accrual: READ_ONLY,
  brc_get_bank_account: READ_ONLY,
  brc_get_cash_payment: READ_ONLY,
  brc_get_cash_receipt: READ_ONLY,
  brc_get_company_api_key_status: READ_ONLY,
  brc_get_company_logo: READ_ONLY,
  brc_get_company_processing_settings: READ_ONLY,
  brc_get_company_reference_settings: READ_ONLY,
  brc_get_company_setup_config: READ_ONLY,
  brc_get_connection_store_diagnostics: READ_ONLY,
  brc_get_customer: READ_ONLY,
  brc_get_customer_opening_balance: READ_ONLY,
  brc_get_deployment_policy: READ_ONLY,
  brc_get_dev_mode_details: READ_ONLY,
  brc_get_financial_year: READ_ONLY,
  brc_get_help_resource_details: READ_ONLY,
  brc_get_nom_ac_ledger_by_ids: READ_ONLY,
  brc_get_nominal_account_ledger_by_id: READ_ONLY,
  brc_get_nominal_journal_batch: READ_ONLY,
  brc_get_payment: READ_ONLY,
  brc_get_prepayment: READ_ONLY,
  brc_get_product: READ_ONLY,
  brc_get_purchase: READ_ONLY,
  brc_get_quote: READ_ONLY,
  brc_get_sales_credit_note: READ_ONLY,
  brc_get_sales_entry: READ_ONLY,
  brc_get_sales_invoice: READ_ONLY,
  brc_get_sales_rep: READ_ONLY,
  brc_get_supplier: READ_ONLY,
  brc_get_supplier_opening_balance: READ_ONLY,
  brc_grouped_nominal_accounts_report: READ_ONLY,
  brc_list_accounts: READ_ONLY,
  brc_list_accruals: READ_ONLY,
  brc_list_allocated_transactions: READ_ONLY,
  brc_list_allocation_resolvers: READ_ONLY,
  brc_list_analysis_categories: READ_ONLY,
  brc_list_audit_log: READ_ONLY,
  brc_list_bank_accounts: READ_ONLY,
  brc_list_book_tran_types: READ_ONLY,
  brc_list_cash_payments: READ_ONLY,
  brc_list_cash_receipts: READ_ONLY,
  brc_list_category_types: READ_ONLY,
  brc_list_company_contexts: READ_ONLY,
  brc_list_company_settings: READ_ONLY,
  brc_list_customer_account_trans: READ_ONLY,
  brc_list_customer_op_bal_trans: READ_ONLY,
  brc_list_customer_quotes: READ_ONLY,
  brc_list_customers: READ_ONLY,
  brc_list_customers_without_dormant: READ_ONLY,
  brc_list_nominal_accounts: READ_ONLY,
  brc_list_nominal_journal_batches: READ_ONLY,
  brc_list_owner_type_groups: READ_ONLY,
  brc_list_owner_types: READ_ONLY,
  brc_list_payments: READ_ONLY,
  brc_list_prepayments: READ_ONLY,
  brc_list_product_types: READ_ONLY,
  brc_list_products: READ_ONLY,
  brc_list_products_without_dormant: READ_ONLY,
  brc_list_purchases: READ_ONLY,
  brc_list_quotes: READ_ONLY,
  brc_list_sales: READ_ONLY,
  brc_list_sales_credit_notes: READ_ONLY,
  brc_list_sales_entries: READ_ONLY,
  brc_list_sales_invoices: READ_ONLY,
  brc_list_sales_reps: READ_ONLY,
  brc_list_supplier_account_trans: READ_ONLY,
  brc_list_supplier_op_bal_trans: READ_ONLY,
  brc_list_suppliers: READ_ONLY,
  brc_list_user_defined_fields: READ_ONLY,
  brc_list_vat_analysis_types: READ_ONLY,
  brc_list_vat_categories: READ_ONLY,
  brc_list_vat_rates: READ_ONLY,
  brc_list_vat_types: READ_ONLY,
  brc_multi_company_nom_ac_report: READ_ONLY,
  brc_open_edu_admin: READ_ONLY,
  brc_process_vat_category_rates: PRIVATE_DESTRUCTIVE,
  brc_red_help: READ_ONLY,
  brc_reopen_quote: PRIVATE_WRITE,
  brc_resolve_book_transaction_type: READ_ONLY,
  brc_route_request: READ_ONLY,
  brc_send_email_statement: EXTERNAL_DESTRUCTIVE,
  brc_send_quote_email: EXTERNAL_DESTRUCTIVE,
  brc_send_sales_invoice_email: EXTERNAL_DESTRUCTIVE,
  brc_set_company_api_key: PRIVATE_DESTRUCTIVE,
  brc_start_company_connection: PRIVATE_WRITE,
  brc_update_accrual: PRIVATE_DESTRUCTIVE,
  brc_update_allocations: PRIVATE_DESTRUCTIVE,
  brc_update_bank_account: PRIVATE_DESTRUCTIVE,
  brc_update_cash_payment: PRIVATE_DESTRUCTIVE,
  brc_update_cash_receipt: PRIVATE_DESTRUCTIVE,
  brc_update_customer: PRIVATE_DESTRUCTIVE,
  brc_update_nominal_journal_batch: PRIVATE_DESTRUCTIVE,
  brc_update_payment: PRIVATE_DESTRUCTIVE,
  brc_update_prepayment: PRIVATE_DESTRUCTIVE,
  brc_update_product: PRIVATE_DESTRUCTIVE,
  brc_update_purchase: PRIVATE_DESTRUCTIVE,
  brc_update_quote: PRIVATE_DESTRUCTIVE,
  brc_update_sales_credit_note: PRIVATE_DESTRUCTIVE,
  brc_update_sales_entry: PRIVATE_DESTRUCTIVE,
  brc_update_sales_invoice: PRIVATE_DESTRUCTIVE,
  brc_update_sales_rep: PRIVATE_DESTRUCTIVE,
  brc_update_supplier: PRIVATE_DESTRUCTIVE,
  brc_validate_transaction_date: READ_ONLY,
} as const satisfies Record<string, ExplicitToolAnnotations>;

export type AnnotatedToolName = keyof typeof TOOL_ANNOTATIONS;

export function getToolAnnotations(toolName: string): ExplicitToolAnnotations {
  const annotations = TOOL_ANNOTATIONS[toolName as AnnotatedToolName];
  if (!annotations) {
    throw new Error(
      `MCP tool "${toolName}" has no explicit safety annotation entry. Add readOnlyHint, openWorldHint, and destructiveHint before registering it.`,
    );
  }

  return annotations;
}
