import assert from "node:assert/strict";
import test from "node:test";
import { randomBytes, randomUUID } from "node:crypto";
import express from "express";
import multer from "multer";
import { registerNormalCompanyManagementRoutes, normalManagementView, resolveNormalManagementContext } from "./normal_company_management.js";
import { renderConnectPage, renderSuccessPage } from "./connection_page.js";
import { getConnectionStore, claimConnectionCodeForSession } from "./connection_store.js";
import { createConnectionSuccessPage, getConnectionSuccessPage } from "./connection_success_session.js";
import { seedClaimableConnection } from "./connection_test_helpers.js";
import { decodeStoredApiKey } from "./credential_secret.js";
import { setCompanyCredentialValidator, resetCompanyCredentialValidator } from "./credential_validation.js";
import { PENDING_CONNECTION_NEVER_EXPIRES_AT } from "./connection_pending.js";

process.env.RED_CONNECT_CONNECTION_STORE = "memory";
process.env.RED_CONNECT_ENCRYPTION_KEY = "test-only-normal-management-encryption";
const token = () => randomBytes(16).toString("hex");

test("normal browser management is scoped, CSRF protected and retains the original confirmation code", async t => {
  setCompanyCredentialValidator(async (_name,key) => key.startsWith("valid-") ? {valid:true} : {valid:false,reason:"invalid_or_expired_api_key",message:"Internal error with invalid-secret"});
  t.after(resetCompanyCredentialValidator);
  const store=getConnectionStore(), connectionId=randomUUID(), otherId=randomUUID();
  const connectToken=token(), confirmationCode=token(), otherConfirmation=token();
  await seedClaimableConnection(store,{connectToken,confirmationCode,connectionId,expiresAt:PENDING_CONNECTION_NEVER_EXPIRES_AT,companies:[{companyName:'A <safe> & "name"',apiKey:"valid-A"},{companyName:"B",apiKey:"valid-B"}]});
  await seedClaimableConnection(store,{connectToken:token(),confirmationCode:otherConfirmation,connectionId:otherId,companies:[{companyName:"Other",apiKey:"valid-other"},{companyName:"B",apiKey:"valid-other-B"}]});
  const success=await createConnectionSuccessPage({confirmationCode,connectedNames:["old snapshot"]});
  const context=await resolveNormalManagementContext("success",success.successId);assert.ok(context);
  assert.equal(context.connectionId,connectionId);
  const app=express();app.set("trust proxy",true);app.use(express.urlencoded({extended:false}));
  app.get("/page",async(req,res)=>{
    const view=await normalManagementView(req,res,context);
    res.send(renderSuccessPage(view.companies,confirmationCode,[],view));
  });
  registerNormalCompanyManagementRoutes(app,multer({storage:multer.memoryStorage(),limits:{fileSize:1024*1024}}).single("companyFile"),value=>Array.isArray(value)?value.map(String).map(v=>v.trim()).filter(Boolean):value==null||value===""?[]:[String(value).trim()]);
  const server=app.listen(0,"127.0.0.1");await new Promise<void>(r=>server.once("listening",r));
  t.after(()=>new Promise<void>(r=>server.close(()=>r())));
  const address=server.address();assert.ok(address&&typeof address!=="string");const base=`http://127.0.0.1:${address.port}`;
  const page=await fetch(base+"/page"),cookie=page.headers.get("set-cookie")!.split(";")[0],html=await page.text();
  const csrf=/name="normalCsrf" value="([^"]+)"/.exec(html)![1];
  assert.match(html,/A &lt;safe&gt; &amp; &quot;name&quot;/);assert.match(html,/>Connected companies</);assert.match(html,/\+ Add another company/);
  assert.match(html,/method="post" action="\/connect\/companies\/disconnect"/);
  assert.match(html,/id="confirmation-code">/);assert.ok(html.includes(confirmationCode));
  for(const secret of ["valid-A","valid-B",connectionId,otherId,"enc:","old snapshot"])assert.ok(!html.includes(secret));
  const securePage=await fetch(base+"/page",{headers:{"x-forwarded-proto":"https"}});
  assert.match(securePage.headers.get("set-cookie")!,/^__Host-red-normal-csrf=/);
  for(const flag of ["HttpOnly","SameSite=Strict","Secure","Path=/"])assert.ok(securePage.headers.get("set-cookie")!.includes(flag));
  const fields={normalContextKind:"success",normalContext:success.successId,normalCsrf:csrf};
  async function post(path:string,extra:Record<string,string>,useCookie=cookie) {
    return fetch(base+path,{method:"POST",headers:{cookie:useCookie,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({...fields,...extra}),redirect:"manual"});
  }
  const disconnect="/connect/companies/disconnect";
  const otherSuccess=await createConnectionSuccessPage({confirmationCode:otherConfirmation,connectedNames:["Other","B"]});
  assert.equal((await post(disconnect,{companyName:"B",confirm:"yes",normalContext:otherSuccess.successId})).status,400,"CSRF is bound to this capability, not only the browser");
  const wrongOrigin=await fetch(base+disconnect,{method:"POST",headers:{cookie,origin:"https://evil.example","content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({...fields,companyName:"B",confirm:"yes"})});
  assert.equal(wrongOrigin.status,400);
  assert.equal((await fetch(base+disconnect)).status,404);
  assert.equal((await post(disconnect,{companyName:"B"},"")).status,400);
  assert.equal((await post(disconnect,{companyName:"B",normalCsrf:"0".repeat(64)})).status,400);
  assert.equal((await post(disconnect,{companyName:"Other",confirm:"yes"})).status,400);
  const before=await post(disconnect,{companyName:"B"});assert.equal(before.status,200);assert.match(await before.text(),/Disconnect B\?/);
  assert.ok(await store.getCredentialForCompany(connectionId,"B"),"first POST only asks for confirmation");
  assert.equal((await post(disconnect,{companyName:"B",confirm:"yes"})).status,303);
  assert.equal(await store.getCredentialForCompany(connectionId,"B"),null);
  assert.ok(await store.getCredentialForCompany(otherId,"B"));
  assert.equal((await store.listConnectedCompanies(connectionId)).length,1);

  const added=await post("/connect/companies",{companyName:"C",apiKey:"valid-C"});assert.equal(added.status,200);
  assert.ok((await added.text()).includes(confirmationCode));
  assert.equal((await store.listConnectedCompanies(connectionId)).length,2);
  const invalid=await post("/connect/companies",{companyName:"C",apiKey:"invalid-secret"});
  const invalidHtml=await invalid.text();assert.doesNotMatch(invalidHtml,/invalid-secret|Internal error/);
  assert.equal(decodeStoredApiKey((await store.getCredentialForCompany(connectionId,"C"))!.encryptedSecret),"valid-C");
  const csv=new FormData();for(const [k,v]of Object.entries(fields))csv.append(k,v);
  csv.append("companyFile",new Blob(["Company Name,API Key\nD,valid-D\nE,valid-E"]),"companies.csv");
  const imported=await fetch(base+"/connect/companies",{method:"POST",headers:{cookie},body:csv});assert.equal(imported.status,200);
  assert.doesNotMatch(await imported.text(),/valid-D|valid-E/);
  assert.equal((await store.listConnectedCompanies(connectionId)).length,4);
  await post("/connect/companies",{companyName:"c",apiKey:"valid-replacement"});
  assert.equal((await store.listConnectedCompanies(connectionId)).length,4);
  assert.equal(decodeStoredApiKey((await store.getCredentialForCompany(connectionId,"C"))!.encryptedSecret),"valid-replacement");
  for(const company of await store.listConnectedCompanies(connectionId))assert.equal((await post(disconnect,{companyName:company.companyName,confirm:"yes"})).status,303);
  assert.equal((await store.listConnectedCompanies(connectionId)).length,0);
  await assert.rejects(claimConnectionCodeForSession(confirmationCode,randomUUID()),/No companies/);
  assert.ok(await store.getConnectionByConfirmationCode(confirmationCode),"empty confirmation must remain unconsumed");
  const empty=await fetch(base+"/page");assert.match(await empty.text(),/Add a company before confirming/);
  await post("/connect/companies",{companyName:"Final",apiKey:"valid-final"});
  assert.equal((await store.getConnectionByConfirmationCode(confirmationCode))!.expiresAt,PENDING_CONNECTION_NEVER_EXPIRES_AT);
  const claimed=await claimConnectionCodeForSession(confirmationCode,randomUUID());assert.deepEqual(claimed.companyNames,["Final"]);
  await assert.rejects(claimConnectionCodeForSession(confirmationCode,randomUUID()),/already been used/);
  assert.equal(await resolveNormalManagementContext("success",success.successId),null);
  assert.deepEqual((await getConnectionSuccessPage(success.successId))!.connectedNames,["Final"]);
  assert.equal((await post(disconnect,{companyName:"Final",confirm:"yes"})).status,400);
  assert.equal((await post("/connect/companies",{companyName:"After claim",apiKey:"valid-late"})).status,400);
  assert.ok(await store.getCredentialForCompany(connectionId,"Final"));
});

test("normal management rejects expired/unknown capabilities and resolves unused pending links only",async()=>{
  const store=getConnectionStore(),pending=token(),connectionId=randomUUID();
  await store.createPendingConnection({connectToken:pending,connectionId,expiresAt:Date.now()+60_000});
  assert.equal((await resolveNormalManagementContext("pending",pending))?.connectionId,connectionId);
  await store.completePendingConnection(pending);
  assert.equal(await resolveNormalManagementContext("pending",pending),null);
  const expired=token();await store.createPendingConnection({connectToken:expired,connectionId,expiresAt:Date.now()-1});
  assert.equal(await resolveNormalManagementContext("pending",expired),null);
  assert.equal(await resolveNormalManagementContext("success",token()),null);
  assert.equal(await resolveNormalManagementContext("ownerId",connectionId),null);
  const page=token();await store.saveConnectionSuccessPage({successId:page,confirmationCode:token(),connectedNames:[],failedCompanies:[],createdAt:0,expiresAt:1});
  assert.equal(await resolveNormalManagementContext("success",page),null);
});
